name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Deploy to DigitalOcean
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.DO_HOST }}
        username: ${{ secrets.DO_USERNAME }}
        password: ${{ secrets.DO_PASSWORD }}
        script: |
          echo "=== Starting deployment ==="
          cd /var/www/PropTradePro
          
          echo "=== Pulling latest code ==="
          git pull origin master || git pull origin main
          
          echo "=== Installing backend dependencies ==="
          cd backend
          pip3 install -r requirements.txt
          
          echo "=== Restarting backend service ==="
          sudo systemctl restart marketedgepros-backend || echo "Backend service not configured yet"
          
          echo "=== Building frontend ==="
          cd ../frontend
          pnpm install
          pnpm run build
          
          echo "=== Restarting frontend service ==="
          sudo systemctl restart marketedgepros-frontend || echo "Frontend service not configured yet"
          
          echo "=== Restarting Nginx ==="
          sudo systemctl restart nginx
          
          echo "=== Deployment completed successfully ==="
          echo "Website: https://marketedgepros.com"

